apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 2
  selector:
    matchLabels:
        app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        teir: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80